# Generated by Django 5.1.5 on 2025-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0010_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='取引相手名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
