# Generated by Django 5.1.5 on 2025-02-17 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0011_alter_counterparty_name_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='counter_party',
            new_name='counterparty',
        ),
        migrations.RemoveField(
            model_name='productrecord',
            name='counterparty',
        ),
        migrations.AddField(
            model_name='productrecord',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrecord',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrecord',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kakeibo.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ConsumptionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='consumption_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.consumptiontax'),
        ),
    ]
