# Generated by Django 5.1.5 on 2025-02-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0013_consumptiontax_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecord',
            name='currency',
        ),
    ]
