# Generated by Django 5.1.5 on 2025-02-28 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0015_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreference',
            new_name='UserPreferences',
        ),
    ]
